mapear_processo:
  description: >
    Revisar os <requisitos> levantados e extrair as informações essenciais 
    sobre os processos de negócios. Isso inclui:

    - Identificar e descrever as atividades principais.
    - Mapeamento das interações entre os diferentes stakeholders.
    - Detalhamento dos fluxos de trabalho e das etapas necessárias para 
    a conclusão de cada processo.
    - Compilação de informações sobre responsáveis, prazos e critérios 
    de sucesso.
    - Elaboração de um documento inicial que organize essas informações 
    de maneira clara e lógica.

    <requisitos>
    {requisitos}
    </requisitos>

  expected_output: >
    O resultado esperado da tarefa é um documento estruturado contendo:
    
    - Uma lista detalhada de atividades e interações.
    - Descrições claras das responsabilidades e fluxos de trabalho.
    - Notas sobre quaisquer considerações especiais que possam impactar 
    a documentação de negócios que será criada posteriormente.

documentar_processo:
  description: >
    Elaborar a documentação não técnica com base nas informações estruturadas 
    fornecidas pelo Agente de Mapeamento de Processos. Isso inclui:

    - Estruturar a documentação de acordo com o <template_padrao> pré-definido, 
    garantindo consistência e facilidade de leitura.
    - Usar uma linguagem simples e acessível, evitando jargões técnicos que possam 
    confundir os leitores. Se jargões forem necessários, incluí-los no Glossário 
    para maior clareza.
    - Incluir seções que expliquem detalhadamente o propósito do processo, 
    as atividades envolvidas, as integrações tecnológicas e as responsabilidades de 
    cada stakeholder.
    - Incorporar exemplos práticos e cenários de aplicação, sempre que possível, 
    para ilustrar os processos e facilitar a compreensão do time de negócios.
    - Garantir que a mantenha um alto padrão de qualidade e profissionalismo.
    - Usar elementos visuais, como tabelas, gráficos de fluxo e diagramas BPMN, 
    para representar as atividades e integrações de forma clara.
    
    <template_padrao>    
      # Nome do Processo
      Apresentação geral do processo, explicando seu objetivo e contexto dentro 
      da empresa. Detalhe quais problemas ele resolve e quais os benefícios para 
      o time de negócios.

      ## Stakeholders
      Lista dos principais envolvidos no processo, suas responsabilidades e o 
      papel de cada um. Exemplos de stakeholders incluem analistas de negócios, 
      gerentes de projeto, e equipes técnicas.

      ## Atividades
      Descrição detalhada de cada atividade envolvida no processo, com suas 
      respectivas validações e fluxo:

      ### Atividade 1: [Nome da Atividade]
        - **Descrição**: Explicação detalhada do que é feito nesta atividade.
        - **Validações**: Critérios que precisam ser atendidos antes que a atividade 
        seja considerada completa.
        - **Fluxo**: Descrição do passo a passo para realizar a atividade, destacando 
        as interações com outros processos ou sistemas.

      ### Atividade N: [Nome da Atividade]
        - **Descrição**: Explicação detalhada do que é feito nesta atividade.
        - **Validações**: Critérios que precisam ser atendidos antes que a atividade 
        seja considerada completa.
        - **Fluxo**: Descrição do passo a passo para realizar a atividade, destacando 
        as interações com outros processos ou sistemas.

      ## Integrações
      Detalhe sobre como o processo se integra com outros sistemas e plataformas, 
      explicando a função de cada integração e sua importância para o sucesso do 
      processo.

      ### Integração 1: [Nome da Integração]
        - **Descrição**: Explicação de como a integração funciona, quais sistemas 
        estão envolvidos e seu papel no processo.

      ### Integração N: [Nome da Integração]
        - **Descrição**: Explicação de como a integração funciona, quais sistemas 
        estão envolvidos e seu papel no processo.

      ## Glossário
      Lista de termos técnicos e seus significados, para garantir que todos os 
    </template_padrao>

  expected_output: >
    Documentação não técnica que contenha:

    - Resumo executivo do processo mapeado, destacando seus objetivos, contexto e 
    benefícios para a empresa.
    - Descrições claras e concisas das atividades, interações e responsabilidades, 
    garantindo que cada etapa do processo seja compreensível para a área de negócios.
    - Um formato visualmente agradável e intuitivo, com uso de listas, tabelas e 
    gráficos de fluxo, facilitando a navegação entre as seções.
    - Seção de glossário, para fornecer explicações adicionais e suportar o 
    entendimento do time de negócios.
    - Garantia de que a documentação está organizada e consistente, sendo uma 
    ferramenta prática para a implementação e monitoramento de soluções.
    
auditar_documentacao:
  description: >
    Revise toda a documentação não técnica produzida pelo Agente de Documentação 
    Técnica. Isso inclui:

    - Verificar a conformidade com o template padrão e os requisitos estabelecidos.
    - Avaliar a clareza e a acessibilidade da linguagem utilizada, garantindo que 
    não haja jargões ou termos técnicos desnecessários.
    - Realizar uma revisão minuciosa em busca de erros gramaticais, ortográficos e de 
    formatação.
    - Fornecer feedback construtivo ao Agente de Documentação Técnica, sugerindo 
    melhorias e ajustes onde necessário.
    - Assegurar que a documentação final seja coerente e que os processos sejam 
    descritos de forma lógica e sequencial.

  expected_output: >
    Relatório de revisão que contenha:

    - Comentários detalhados sobre a qualidade da documentação.
    - Sugestões de melhorias para garantir a conformidade com o template e as 
    melhores práticas de escrita.
    - Uma lista de correções necessárias, com referência a seções específicas da 
    documentação.
    - **A documentação final revisada, aprovada e pronta para ser entregue ao time 
    de negócios.**

coordenar_comunicacao:
  description: >
    Garanta que a comunicação flua de maneira eficaz entre todos os membros da equipe. 
    Isso inclui:

    - Organizar e moderar reuniões regulares para discutir o progresso do projeto e 
    quaisquer desafios enfrentados.
    - Facilitar a troca de feedbacks entre os agentes, assegurando que todos os pontos 
    de vista sejam considerados.
    - Documentar decisões importantes e ações acordadas durante as reuniões.
    - Promover um ambiente de colaboração onde os agentes se sintam à vontade para 
    compartilhar ideias e preocupações.
    - Acompanhar o progresso das tarefas e oferecer suporte sempre que necessário, 
    garantindo que as metas do projeto sejam atingidas.

  expected_output: >
    O resultado esperado da tarefa é:

    - Um registro de reuniões que inclua pautas, notas e decisões tomadas.
    - Uma lista de ações acordadas e responsáveis por sua execução.
    - Relatórios regulares sobre o andamento do projeto, destacando conquistas 
    e áreas que precisam de atenção.
    - Um ambiente de trabalho positivo e colaborativo, onde os agentes se sintam 
    motivados e engajados.
