mapear_processo:
  description: >
    Revisar os <requisitos> levantados e extrair as informações essenciais 
    sobre os processos de negócios. Isso inclui:

    - Identificar e descrever as atividades principais.
    - Mapeamento das interações entre os diferentes stakeholders.
    - Detalhamento dos fluxos de trabalho e das etapas necessárias para 
    a conclusão de cada processo.
    - Compilação de informações sobre responsáveis, prazos e critérios 
    de sucesso.
    - Elaboração de um documento inicial que organize essas informações 
    de maneira clara e lógica.

    <requisitos>
    {requisitos}
    </requisitos>

  expected_output: >
    O resultado esperado da tarefa é um documento estruturado contendo:
    
    - Uma lista detalhada de atividades e interações.
    - Descrições claras das responsabilidades e fluxos de trabalho.
    - Notas sobre quaisquer considerações especiais que possam impactar 
    a documentação de negócios que será criada posteriormente.

documentar_processo:
  description: >
    Elaborar a documentação não técnica com base nas informações 
    estruturadas fornecidas pelo Agente de Mapeamento de Processos. 
    Isso inclui:

    - Estruturar a documentação de acordo com <template_padrao> 
    pré-definido.
    - Usar uma linguagem simples e acessível, evitando jargões técnicos 
    que possam confundir os leitores.
    - Incluir seções que expliquem o propósito de cada processo, as 
    atividades envolvidas, e as responsabilidades de cada stakeholder.
    - Incorporar exemplos práticos, sempre que possível, para ilustrar os 
    processos e facilitar a compreensão.
    - Garantir que a documentação seja revisada e esteja livre de erros, 
    mantendo um padrão de qualidade.

    <template_padrao>
    # Nome do Processo

    ## Stackholder

    ## Atividades

    ### Atividade 1
      - Descrição
      - Validações
      - Fluxo

    ### Atividade N
      - Descrição
      - Validações
      - Fluxo

    ## Integrações

    ### Integração 1
     - Descrição

    ### Integração N
     - Descrição
    </template_padrao>

  expected_output: >
    Documentação não técnica que contenha:

    - Um resumo executivo do processo mapeado, destacando seus objetivos 
    e benefícios.
    - Descrições claras e concisas das atividades, interações e 
    responsabilidades.
    - Um formato visualmente agradável, com uso de listas, tabelas e 
    gráficos, onde aplicável.
    - Anexos ou referências adicionais que possam ser úteis para o time de 
    negócios, como FAQs ou glossários.
    
auditar_documentacao:
  description: >
    Revise toda a documentação não técnica produzida pelo Agente de Documentação 
    Técnica. Isso inclui:

    - Verificar a conformidade com o template padrão e os requisitos estabelecidos.
    - Avaliar a clareza e a acessibilidade da linguagem utilizada, garantindo que 
    não haja jargões ou termos técnicos desnecessários.
    - Realizar uma revisão minuciosa em busca de erros gramaticais, ortográficos e de 
    formatação.
    - Fornecer feedback construtivo ao Agente de Documentação Técnica, sugerindo 
    melhorias e ajustes onde necessário.
    - Assegurar que a documentação final seja coerente e que os processos sejam 
    descritos de forma lógica e sequencial.

  expected_output: >
    Relatório de revisão que contenha:

    - Comentários detalhados sobre a qualidade da documentação.
    - Sugestões de melhorias para garantir a conformidade com o template e as 
    melhores práticas de escrita.
    - Uma lista de correções necessárias, com referência a seções específicas da 
    documentação.
    - **A documentação final revisada, aprovada e pronta para ser entregue ao time 
    de negócios.**

coordenar_comunicacao:
  description: >
    Garanta que a comunicação flua de maneira eficaz entre todos os membros da equipe. 
    Isso inclui:

    - Organizar e moderar reuniões regulares para discutir o progresso do projeto e 
    quaisquer desafios enfrentados.
    - Facilitar a troca de feedbacks entre os agentes, assegurando que todos os pontos 
    de vista sejam considerados.
    - Documentar decisões importantes e ações acordadas durante as reuniões.
    - Promover um ambiente de colaboração onde os agentes se sintam à vontade para 
    compartilhar ideias e preocupações.
    - Acompanhar o progresso das tarefas e oferecer suporte sempre que necessário, 
    garantindo que as metas do projeto sejam atingidas.

  expected_output: >
    O resultado esperado da tarefa é:

    - Um registro de reuniões que inclua pautas, notas e decisões tomadas.
    - Uma lista de ações acordadas e responsáveis por sua execução.
    - Relatórios regulares sobre o andamento do projeto, destacando conquistas 
    e áreas que precisam de atenção.
    - Um ambiente de trabalho positivo e colaborativo, onde os agentes se sintam 
    motivados e engajados.
