[tool.poetry]
name = "instituto-crewai"
version = "0.1.0"
description = ""
authors = ["rodrigo.goncalves"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<=3.13"
crewai = {extras = ["tools"], version = "^0.35.7"}
python-dotenv = "^1.0.1"
textwrap3 = "^0.9.2"
langchain-google-genai = "1.0.4"
google-generativeai = "0.5.4"
pyyaml = "^6.0.1"
langchain-huggingface = "^0.0.3"
langchain-groq = "0.1.5"
langchain_community = "0.0.29"
ipykernel = "^6.29.5"
flask = "^3.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
