[tool.poetry]
name = "instituto-crewai"
version = "0.1.0"
description = ""
authors = ["rodrigo.goncalves"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<=3.13"
crewai = {extras = ["tools"], version = "^0.35.7"}
python-dotenv = "^1.0.1"
textwrap3 = "^0.9.2"
langchain-google-genai = "1.0.3"
google-generativeai = "0.5.2"
pyyaml = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
