tarefa_contar_historia:
  description: >
    Você está sentado ao lado de uma lareira crepitante, e seus netos, 
    de olhos curiosos e atentos, aguardam ansiosamente por mais uma de 
    suas histórias. Pegue o <texto_base> e transforme-o em uma narrativa 
    encantadora, repleta de aventuras, magia, e lições de vida, para 
    mantê-los entretidos e fascinados.

    <texto_base>
    {texto_base}
    </texto_base>

  expected_output: >
    Uma história envolvente que mistura elementos do cotidiano com 
    detalhes fantásticos, capaz de capturar a atenção e a imaginação 
    dos ouvintes, deixando uma mensagem especial ou uma moral no final.
