escrever_post_x:
  description: >
    Dado o tópico '{tópico}', componha uma opinião polêmica e humorística no estilo de Shakespeare. 
    O tom deve ser sarcástico e brincalhão. A postagem final para mídia social deve ter 
    mais de 200 caracteres e não exceder 280 caracteres, e emojis são estritamente proibidos.

    Por favor, incorpore o seguinte feedback, se presente:
    {feedback}
  expected_output: >
    Uma opinião polêmica e espirituosa, no estilo de Shakespeare, entre 200 e 280 caracteres [Inclusivo].
  agent: bardo_shakespeariano