tarefa_pesquisa:
  description: >
    Realize uma pesquisa aprofundada sobre o cliente e os concorrentes no contexto
    de {dominio_cliente}.
    Certifique-se de encontrar informações interessantes e relevantes, considerando
    que o ano atual é 2024.
    Estamos trabalhando com eles no seguinte projeto: {descricao_projeto}.
  expected_output: >
    Um relatório completo sobre o cliente, seus clientes e concorrentes,
    incluindo suas demografias, preferências, posicionamento de mercado e engajamento do público.

tarefa_compreensao_projeto:
  description: >
    Compreenda os detalhes do projeto e o público-alvo para
    {descricao_projeto}.
    Revise qualquer material fornecido e reúna informações adicionais conforme necessário.
  expected_output: >
    Um resumo detalhado do projeto e um perfil do público-alvo.

tarefa_estrategia_marketing:
  description: >
    Formule uma estratégia de marketing abrangente para o projeto
    {descricao_projeto} do cliente {dominio_cliente}.
    Utilize os insights da tarefa de pesquisa e da tarefa de compreensão do projeto
    para criar uma estratégia de alta qualidade.
  expected_output: >
    Um documento detalhado de estratégia de marketing que descreva os objetivos, o público-alvo,
    as mensagens-chave e as táticas propostas. Certifique-se de incluir nome, táticas, canais e KPIs.

tarefa_ideia_campanha:
  description: >
    Desenvolva ideias criativas de campanhas de marketing para {descricao_projeto}.
    Certifique-se de que as ideias sejam inovadoras, envolventes e alinhadas com a estratégia de marketing geral.
  expected_output: >
    Uma lista de 5 ideias de campanhas, cada uma com uma breve descrição e impacto esperado.

tarefa_criacao_texto:
  description: >
    Crie textos de marketing com base nas ideias de campanha aprovadas para {descricao_projeto}.
    Certifique-se de que os textos sejam atraentes, claros e adaptados ao público-alvo.
  expected_output: >
    Textos de marketing para cada ideia de campanha.