plano_task:
  description: >
    1. Priorize as últimas tendências, principais players e notícias 
    relevantes sobre {topico}.
    
    2. Identifique o público-alvo, considerando seus interesses e 
    pontos de dor.
    
    3. Desenvolva um plano de conteúdo detalhado, incluindo uma introdução, 
    pontos principais e um chamado à ação.
    
    4. Inclua palavras-chave de SEO e dados ou fontes relevantes.
  expected_output: >
    Um documento de plano de conteúdo para {n} posts sobre {topico}, contendo 
    um esboço, análise do público, palavras-chave de SEO e recursos relevantes.

pesquisa_task:
  description: >
    Pesquise as últimas tendências sobre {topico}, focando em novidades 
    e inovações na área de tecnologia.
  expected_output: >
    Um relatório detalhado sobre as tendências mais recentes sobre {topico} 
    na área de tecnologia, incluindo insights relevantes e fontes.

escrita_task:
  description: >
    Escreva {n} postagens envolventes em português do Brasil com base nas 
    tendências pesquisadas sobre {topico}. Cada post deve ter entre 250 
    e 350 palavras.
    
    Cada post deve ser formatado como:
    \n\nPOST:\ntexto do post em português do brasil
    \n\nPROMPT:\nprompt da imagem desse post\n\n
  expected_output: >
    {n} postagens bem escritas, atraentes e em português do Brasil, formatadas 
    conforme especificado, abordando o tópico {topico}.

criacao_imagem_task:
  description: >
    Crie {n} prompts para gerar imagens atraentes que acompanhem as postagens 
    no Instagram sobre {topico}.
  expected_output: >
    {n} prompts de alta qualidade para criação de imagens adequadas ao Instagram, 
    baseados no tópico {topico}.


revisao_task:
  description: >
    Revise os textos e prompts de imagens para as {n} postagens no Instagram, 
    garantindo que as informações estejam organizadas, sem erros e cativantes, 
    em português do Brasil, sobre {topico}.

    Certifique-se de que cada post está formatado como:
    \n\nPOST:\ntexto do post em português do brasil
    \n\nPROMPT:\nprompt da imagem desse post\n\n
  expected_output: >
    {n} textos e prompts de imagens revisados e organizados, prontos para serem 
    publicados em português do Brasil, formatados conforme especificado.